before_script:
  - npm install -g gulp
  - npm install
script: gulp
after_success: coveralls
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start